services:
  postgres:
    image: postgres:latest
    container_name: postgres_tsaas_localhost
    restart: always
    ports:
      - "5433:5432" # host port different from RDS AWS (5432)
    environment:
      POSTGRES_USER: admin    
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tsaas_localhost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
