services:
  postgres:
    image: postgres:latest
    container_name: postgres_tsaas_localhost
    restart: always
    ports:
      - "5433:5432" # host port different from RDS AWS (5432) ; <external port>:<internal port>
    environment:
      POSTGRES_USER: admin    
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tsaas_localhost_db
    volumes:
      - ./dados_pg:/var/lib/postgresql/data

# note: 
# Left port (5433): acess host (localhost)
# Right port (5432): access container (postgres)